name: A workflow for building Buildroot artifacts
on: push

jobs:
  build:
    name: Build system
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/nerves-project/nerves_system_br:1.28.2
      options: --user root
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup cache
        id: cache-buildroot-downloads
        uses: actions/cache@v3
        with:
          path: _build/dl
          key: buildroot-${{ hashFiles('Makefile') }}

      - name: Build
        run: |
          sudo -u nerves make

      - name: Upload Artifacts and Create Release
        if: contains(github.ref, 'tags')
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: _build/output/images/*
          file_glob: true
          tag: ${{ github.ref }}


